### ISSUE TITLE
Request to add this homebrew to the Universal DB

### ISSUE THREAD

**Issue by ghost** [Core-2-Extreme/Line_for_3DS#4]
これはUniversal Updaterのウェブサイトだ. [](https://db.universal-team.net/
)これはアップリクエストフォームのウェブサイトだ: [](https://github.com/Universal-Team/db/issues/new?assignees=&labels=app+request&template=app-request.md
)
よろしくお願いいたします！
core-2-extremeさんの3DSホームブルはめっちゃ素晴らしいだよ。

**Comment by Core-2-Extreme** [comment]
added
