### ISSUE TITLE
Code for app scripts not viewable

### ISSUE THREAD

**Issue by CoolLondos** [Core-2-Extreme/Line_for_3DS#5]

**Comment by CoolLondos** [comment]
im on a 3ds its hard to type but ill explain (ps: i cant add a description bc im on 3ds): when i try to view the code part of the google app script, it shows this: ΄404: not found.'.

**Comment by Core-2-Extreme** [comment]
Setup instruction for v2.0.0 has a dead link, please use setup instruction  for v2.0.0.1 https://github.com/Core-2-Extreme/Line_for_3DS/blob/v2.0.0.1/SETUP.md

(Setup instruction v2.0.0 and v2.0.0.1 are completely same expect dead link)
